### ISSUE TITLE
Strange results pressure-wise when stacking compartments

### ISSUE THREAD

**Issue by pimzzff1** [firemodels/cfast#2004] opened 2022-09-27 12:38 UTC
Hi,

Currently running a case where I need to stack compartments and connect them by horizontal vents. The case immediatly gives significant underpressure, which are not expected when looking at the case. As a result, vent flows are also not approximated correctly. Tried to simplify the case as shown in the appendix (case '2'). 

When the top compartment is removed (case '1'), the case runs as expected. Hoping someone can shed some light on this one.

Using CFAST version 7.7.3. 
Update: tried running the same case in 7.7.0 and it gave more realistic pressures.

Kind regards, 
Pim
[1.txt](https://github.com/firemodels/cfast/files/9655843/1.txt)
[1_compartments.csv](https://github.com/firemodels/cfast/files/9655844/1_compartments.csv)
[1_vents.csv](https://github.com/firemodels/cfast/files/9655845/1_vents.csv)
[2.txt](https://github.com/firemodels/cfast/files/9655846/2.txt)
[2_compartments.csv](https://github.com/firemodels/cfast/files/9655847/2_compartments.csv)
[2_vents.csv](https://github.com/firemodels/cfast/files/9655849/2_vents.csv)

**Comment by mcgratta** [comment] 2022-09-27 13:28
I ran both cases. The mass flows through the vents look OK. 

Rick, Paul -- does CFAST report the pressure at the floor of each compartment? Perhaps the pressure drop is due to the vertical location.

**Comment by rpeacoc** [comment] 2022-09-27 13:46
It does report the pressure at floor level, relative to exterior ambient at that height. I’ll look at casesSent from my iPhoneOn Sep 27, 2022, at 9:28 AM, Kevin McGrattan ***@***.***> wrote:﻿
I ran both cases. The mass flows through the vents look OK.
Rick, Paul -- does CFAST report the pressure at the floor of each compartment? Perhaps the pressure drop is due to the vertical location.

**Comment by preneke** [comment] 2022-09-27 13:58
The fire is in compartment 2. Basically as soon as the fire starts, time 0 s in this case, in Comp 2 the pressure at the floor drops. That is just how fires work. The pressure in comp 1 will also drop. Keep in mind the pressure is the pressure at the floor of the relative compartment.

Paul

From: pimzzff1 ***@***.***>
Sent: Tuesday, September 27, 2022 8:39 AM
To: firemodels/cfast ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [firemodels/cfast] Strange results pressure-wise when stacking compartments (Issue #2004)


Hi,

Currently running a case where I need to stack compartments and connect them by horizontal vents. The case immediatly gives significant underpressure, which are not expected when looking at the case. As a result, vent flows are also not approximated correctly. Tried to simplify the case as shown in the appendix (case '2').

When the top compartment is removed (case '1'), the case runs as expected. Hoping someone can shed some light on this one.

Kind regards,
Pim
1.txt<https://github.com/firemodels/cfast/files/9655843/1.txt>
1_compartments.csv<https://github.com/firemodels/cfast/files/9655844/1_compartments.csv>
1_vents.csv<https://github.com/firemodels/cfast/files/9655845/1_vents.csv>
2.txt<https://github.com/firemodels/cfast/files/9655846/2.txt>
2_compartments.csv<https://github.com/firemodels/cfast/files/9655847/2_compartments.csv>
2_vents.csv<https://github.com/firemodels/cfast/files/9655849/2_vents.csv>

-

**Comment by pimzzff1** [comment] 2022-09-27 14:21
Thanks for replying on such short notice! Much appreciated.

Off course we can expect the pressure to drop at floorlevel in the fire compartment. The rate at which it drops however, is extreme given the imposed HRR (e.g. from 0 to -40 Pa in 15 seconds while the HRR is barely 3 kW). The relative pressure in the other compartments shows the same trend. 

Also, the inlet in the lower level shows mass being exhausted while the opening between the two stacked compartments shows a mass flow from the highest to the lowest. It doesn't add up.

I could very well be missing something.

**Comment by preneke** [comment] 2022-09-28 13:14
I am sorry. I didn't realize it was two cases. I have looked at it and yes there seem to be some problems. We are working on it and will get back to you as soon as we can.

Paul

**Comment by preneke** [comment] 2024-02-21 13:49
This problem has been fixed. The problem is that pressure and density within a fixed volume at a fixed temperature has a constant relationship, i.e., pressure/density = constant. In CFAST we assume that the change in density is sufficiently small that we can just calculate the change in pressure due to height as -rho*g*h. In residential type dimensions, especially elevation this isn't too bad and any small differences are dominated by the fire. However, when you have large differences in heights and 20 m meets that criteria this has problems. For example assume a compartment h above the reference height. The pressure at the floor of the compartment is P_0 - rho_0*g*h. To be consistent within the compartment for the differential equations we calculate the density in the compartment as rho_c using the pressure P_0-rho*g*h. Now rho_c < rho but the pressure at the floor of the compartment and at the compartment level outside are the same. So as we go up from the floor of the compartment since rho_c < rho the pressure drop is less and so CFAST calculates a flow out even though there should be no flow. The solution is to calculate the external temp and pressure at the floor of each compartment and use that value for calculations across vents connected to the outside. 

I am closing this issue.

**Closed by preneke** 2024-02-21 13:49 UTC
