### ISSUE TITLE
Apparent problem with energy balance with door jet fires

### ISSUE THREAD

**Issue by GoogleCodeExporter** [firemodels/cfast#122] opened 2015-06-25 13:52 UTC
```
Start with a large fire in a small compartment with sufficiently small vents so 
that a door jet fire is generated into a second compartment.  If the HoC of the 
fire is very low or there are multiple fires with different HoC values, the 
total HRR adding up the original fire and any door jet fires can exceed the 
original input HRR

This seems to be a problem with the assumption that all door jet fires use a 
HoC of methane since the actual HoC of the door jet is unknown. See line 791 of 
fire.f90.

We should be able to resolve this by adjusting all fires to an effective single 
HoC, adjusting mdots (so correct amount of heat is released) and yields (so 
correct mass of species is generated). This is consistent with FDS
```

Original issue reported on code.google.com by `cfastdev@gmail.com` on 3 Oct 2014 at 4:52

**Comment by rpeacoc** [comment] 2017-06-16 15:26
Closed as a duplicate of Issue #144

**Closed by rpeacoc** 2017-06-16 15:26 UTC
Labels: auto-migrated, bug, Component-CFAST, Component-Logic, Priority-Medium, Type-Defect
